### ISSUE TITLE
实例篇"github_client_app"，运行后登录不了，报错

### ISSUE THREAD

**Issue by wenhuichen** [wendux/flutter_in_action_source_code#2]
flutter: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Operation timed out, errno = 60, address = 10.1.10.250, port = 54615

**Comment by ghost** [comment]
去掉dio的代理设置就好，或者你用release模式运行，就不会跑到代理里面

**Comment by jhwsx** [comment]
@TangYuanHuan 我使用了 release 模式运行，报错了：
```text
I/flutter (29408): DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'api.github.com' (OS Error: No address associated with hostname, errno = 7)
```
