### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by ghost** [wendux/flutter_in_action_source_code#6]
报错位置
lib/common/git_api.dart
报错方法

// 登录接口，登录成功后返回用户信息
  Future<User> login(String login, String pwd) async {
   
  }

打印的日志

login e:DioError [DioErrorType.RESPONSE]: Http status error [404]

**Comment by SuperManHa** [comment]
你登录的时候用的你的邮箱，换成你的用户名（TangYuanHuan）就行了。
还有就是删掉你的log日志，能解码出密码明文的。

**Comment by ghost** [comment]
> 你登录的时候用的你的邮箱，换成你的用户名（TangYuanHuan）就行了。
> 还有就是删掉你的log日志，能解码出密码明文的。

谢谢，能登录，看来我要改一下密码了，-_-！
